name: build

on: [ workflow_dispatch ]

jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['^1.20']
    steps:
      - uses: actions/checkout@v3

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: build
        run: sh ./build/package/build.sh

      - name: upload build file
        uses: actions/upload-artifact@v3
        with:
          name: go-build-data
          path: binary
